### ISSUE TITLE
unable to save illustrator files  - error ID: -54 [file is already opened]

### ISSUE THREAD

**Issue by didrip** [haiwen/seadrive-gui#118]
I have the same issue on 2 different computers where an opened file cannot be saved onto seadrive, it eventually works after some time or after saving it somewhere else and copying it back to desired location.

![error-54](https://user-images.githubusercontent.com/18724661/57870891-5bfeaf80-7808-11e9-9b8d-6cdf39bce450.png)

It seems to happen when the file uses dynamic links (between Adobe Illustrator and Adobe After Effects).

- illustrator cc 2019
- seadrive 1.0.3
- windows 1809

**Comment by monkeydri** [comment]
Below the possibly related logs `seadrive.log` :

```
[03/26/19 10:08:06] sync-mgr.c(572): Repo 'library' sync state transition from 'synchronized' to 'committing'.
[03/26/19 10:08:06] file-cache-mgr.c(2178): Failed to stat C:/Users/username/seadrive/data\file-cache\788520a8-60e4-4b19-b496-5a858c764478\SOME DIRECTORY/5_Animation/AEtemp-283701-PROJECT_V01.aep: No such file or directory.
[03/26/19 10:08:06] sync-mgr.c(2394): Failed to index file SOME DIRECTORY/5_Animation/AEtemp-283701-PROJECT_V01.aep in repo 788520a8-60e4-4b19-b496-5a858c764478, skip.
[03/26/19 10:08:06] sync-mgr.c(2704): All operations of repo library(788520a8) have been processed.
```

**Comment by killing** [comment]
Thank you for reporting. What do you mean by dynamic links?

**Comment by monkeydri** [comment]
Dynamic links are a feature of Adobe software, you open a file in Adobe Illustrator (vector graphics) and this file is used as "dynamic link" in Adobe After Effects (motion design). Then when you edit the vector in Illustrator and save it appears instantly in After Effects.

I would like to provide additional info but I don't know where to look for.

**Comment by killing** [comment]
Which file cannot be saved? Say you have file A linking to file B, which one cannot be saved? Are there any error reported in Adobe software? Or the content is just not saved silently?

**Comment by monkeydri** [comment]
The currently opened Illustrator file (with links to object in other files) cannot be saved, the error shown in Adobe Illustrator is "cannot save this file, it is currently used by another program/user"(*).

It works after repeatedly trying to save (dismissing the error popup and trying again) after something like 4-5 times. 

(*) : I will update this comment with the exact error message once I get it again.

**Comment by monkeydri** [comment]
I updated the top post  with the error code.

Similar error is reported here : [https://forums.adobe.com/thread/1027103](https://forums.adobe.com/thread/1027103) when people trying to save illustrator file on google drive.

After some testing this error is not related with Adobe dynamic links (also happens with standalone .ai files).
This happens while file is not previewed in Explorer.

It seems that the seadrive sync process blocks the save. This can be very bad because sometimes one might just dismiss the window without trying again to save (we already lost data because of this bug).


- illustrator cc 2019
- seadrive 1.0.4
- windows 1809

**Comment by ydixt** [comment]
Actually the same error happens in Notepad when preview pane is opened.

**Comment by killing** [comment]
Hi @ydixt 

Thank you for the information. We now found the cause of the issue. It's due to the fact that we map the virtual drive as as removable disk. Mapping it as local disk doesn't have the issue.

We map the virtual drive as removable disk to avoid aggressive download behavior of Windows explorer when opening a folder with many pictures. We'll map the drive as local after we develop an explorer plugin to avoid the aggressive download issue.

**Comment by ydixt** [comment]
Ok thank you very much for your feedback ! Yes this is not a big deal now as saving works on second attempt but it is a bit annoying (I tell users not to use preview pane but they tend to forget it !)
