### ISSUE TITLE
Cannot preview with spacebar (quicklook) .ai files (Illustrator) after Seadrive 1.0.8 update

### ISSUE THREAD

**Issue by didrip** [haiwen/seadrive-gui#149]
On 3 different machines :

- Illustrator 24.0 on macOS 10.14.6 (macbook-pro)
- Illustrator 24.0 on macOS 10.14.6 (mac-mini)
- Illustrator 23.0.4 on macOS 10.14.5 (macbook-air)

Works with local files, files on Network share (smb://) and files on Synology drive.

Preview is just blank (white). Used to work fine before with version 1.0.4 (can be downloaded [here](https://we.tl/t-JITEjbrbGJ)).

**Comment by lins05** [comment]
This is expected behavior. The reason is on macOS Finder would try to generate thumbnails for some of the file types (.jpg, .png, .mp4, .ai) etc, and it would ask seadrive to download the whole content of these files even if the user doesn't have the intention to do that. 

To avoid this behavior, seadrive registers itself as the quicklook generator for these file types, and it would only show a thumbnail/preview of them when it has a local cache.
