### ISSUE TITLE
Seafile Drive Client for Mac Issue

### ISSUE THREAD

**Issue by armanmisdar** [haiwen/seadrive-gui#43]
I always encountered this messages while working on my MS Word 2011:

**"Word cannot save this document due to a naming or permissions error on the destination volume"**

The same issue also happening while working on MS Excel.

My system is Mac El Capitan 10.11.6 running Seafile Drive Client version 0.8.0

I understand it still a beta but would like to report so that this issue can be fixed in future version.

You can see the attachment for the error that appears. Thank you!

![whatsapp image 2017-11-23 at 07 23 36](https://user-images.githubusercontent.com/33924443/33163428-6a54eab0-d069-11e7-92ba-d53bc85c914b.jpeg)

**Comment by killing** [comment]
Hi @armanmisdar Do you have any error message in seadrive.log when this happenes?

**Comment by corradofiore** [comment]
Hi,

I am experiencing the same problem here.  I am Trying to offload some of the libraries on my Mac using the Seafile Drive, but I can not copy data onto the Seadrive mount.

### System

Mac OS X 10.11.6 'El Capitan'
Seafile Drive 0.9.4

### Steps to reproduce

1.  Create a library in Seafile
2.  mount it using the Seafile Drive Client for Mac OS X v0.9.4
3.  In the Finder, copy an *application* to the mounted drive, e.g. "Photo Booth.app".

I understand this might seem like an unusual case, but there are applications like Photos.app that put all of their data in an application bundle rather than in a separate regular folder.  A small application bundle like Photo Booth.app is handy for triggering the problem without moving huge amounts of data.

### Expected result

1.  The application bundle (technically, still a folder) is copied to the Seafile Drive mount.
2.  Symlinks are expected to be kept as such (e.g. a symbolic link in an application package, pointing to /Library/something should still do so).  In other words, we would expect the mounted drive to behave like any external drive attached to the Mac.

### Actual results

1.  The copy process returns an error -43 ("The operation can't be completed because one or more required items can't be found") almost immediately.
2.  The application bundle is copied only partially.
3.  Seafile Drive logs do not report anything peculiar
4.  Also Mac OS X logs are quiet

### Other notes

If we repeat the copy process via CLI using Rsync, we can see that it chokes on a single symbolic link:

```
$ rsync -avH --delete --progress /Applications/Photo\ Booth.app  /Users/username/SeaDrive/My\ Libraries/Pictures 

building file list ... 
582 files to consider
Photo Booth.app/
Photo Booth.app/Contents/
[...]

Photo Booth.app/Contents/Resources/PhotoBooth.help/Contents/Resources/
rsync: symlink "/Users/username/SeaDrive/My Libraries/Pictures/Photo Booth.app/Contents/Resources/PhotoBooth.help/Contents/Resources/index.html" -> "/Library/Documentation/Resources/Eagle/index.html" failed: No such file or directory (2)

[...]
Photo Booth.app/Contents/_CodeSignature/CodeResources
      185680 100%  251.15kB/s    0:00:00 (xfer#499, to-check=0/582)

sent 6364501 bytes  received 11490 bytes  2550396.40 bytes/sec
total size is 6325553  speedup is 0.99
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-47/rsync/main.c(992) [sender=2.6.9]
```

As an aside, the linked file exists:

```
$ ls -alh /Library/Documentation/Resources/Eagle/index.html
-rw-r--r--  1 root  wheel    80K 10 Jul  2015 /Library/Documentation/Resources/Eagle/index.html
```

Hope this helps.

**Comment by killing** [comment]
Copying Application folder into SeaDrive is not supported for now.
