### ISSUE TITLE
Revert library categories introduced in 0.9.0

### ISSUE THREAD

**Issue by 92lleo** [haiwen/seadrive-gui#64]
Hi Seafile Team,
Please revert "_Libraries are displayed under three folders "My Libraries", "Group Libraries", "Shared libraries"_" back to all libs or add a checkbox to switch between both. For me (and others I've asked) it's adding a unnecesarry additional step to browsing libraries. Not showing all (for the user visible) libraries is frustrating on the web interface, too. 

Thanks

**Comment by supercosh** [comment]
Would definitively also urge for such an option in the drive client. With the change introduced in 0.90, all shortcuts to our files are broken. Also, we have learned from various users that the names of these folders are confusing: most users don't see the difference between Group folders and Shared folders. 

Or would it be possible to set a "deep" mountpoint link when specifying the server address?

Thanks!

**Comment by freeplant** [comment]
What do you mean by "deep" mountpoint link?

**Comment by monkeydri** [comment]
Well I think this change back to previous structure will never happen, because it is a big one which involves a change on [seafile-server](https://github.com/haiwen/seadrive-server) too and probably on seadrive (non-gui part not open sourced) too.

It was introduced by d1cde2767be13b3b68d45523e953ad78be755293

I don't understand the rationale behind it because it makes everything complicated without adding anything, plus it breaks file paths when changing the way a library is shared (ex, shared to a user within a group then sharing to this user directly), it is the one thing which sucks on seadrive to me. Why don't work just like dropbox ?

**Comment by oddgames-david** [comment]
I'd like them to provide the option to define the structure a bit. The current structure really is odd.

**Comment by MurzNN** [comment]
When users connecting to SeaFile via WebDAV protocol, they see plain list of libraries as regular folders, without strange structure, that splitting libraries between My Libraries’, ‘Shared with all’, ‘Shared with groups’, ‘Shared with me’!

Please add option to SeaDrive clients for give back plain structure of library folders!

**Comment by MurzNN** [comment]
Seems the source of this change is described here https://forum.seafile.com/t/shared-libraries-with-similar-equal-names-generate-conflicts-with-the-drive-client/2569

But the solution is bad! Instead of creating unneeded subfolders, better is make unique names via numeric suffixes: "Nonuniquelibname", "Nonuniquelibname (1)", "Nonuniquelibname (2)", etc

**Comment by MurzNN** [comment]
Better solution that numbers is add library owner to duplicated folders: "Nonuniquelibname", "Nonuniquelibname (alice)", "Nonuniquelibname (bob)

**Comment by kocane** [comment]
A bit of a shame this decision was made. The simple structure that was there before, really was a plus. Seperating all this into 4 folders hardly makes it any less complicated. I think @MurzNN is onto something with his suggestion of naming in the case of duplicates or atleast make it an optional option.

**Comment by MurzNN** [comment]
@killing can you please describe the reasons why Seafile don't want to fix this annoying behavior, instead of silently closing this issue?

**Comment by killing** [comment]
We don't have plan to add back the old structure. It makes the code too complicated to maintain.

**Comment by supercosh** [comment]
Too bad this issue has been closed now. This was always the reason for us not to update from version 0.9.6 on. Otherwise all links would not work anymore and the effort to adjust all links would be too big for us. A workaround for us was, to remount the directories with a simple "subst" command on windows startup. However, this is very hacky, since the seadrive contents are not instantly available after login, so we just put a sleep(30) command in there. Well, that would all not have been necessary, if the issue would have been fixed. I still don't understand why this was introduced.

**Comment by MurzNN** [comment]
In our company current Seafile structure is too hard to understand for most of employees and produce many problems for each newbie! They always ask each other, that don't see new folder, that somebody share to him, because they lookup at first in `My library` folder, and don't see it. But for find new shared library - they now must lookup in three other places: `Shared with all`, `Shared with groups`, `Shared with me` for find needed library, and I, as sysadmin, already tired to describe this "feature" for each new employee :(

So, I think, that easy to understand UX must surpass code complexity!

**Comment by MurzNN** [comment]
Maybe, as workaround, you can implement virtual `All available libraries` folder, that will have symlinks to all libraries from all groups?

**Comment by supercosh** [comment]
+1 for MurzNN's suggestion for the virtual folder, and additional to this, create a configuration option in the client GUI to set an "entry path" as filedrive root. So the users would have the drive S: with the contents of the virtual directory mentioned above. This is what we are doing today with the subst command.
